# Generated by Django 3.2 on 2023-01-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='x', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
